export const GET_MOVIES = 'GET_MOVIES';
export const POST_SELECTED_MOVIES = 'POST_SELECTED_MOVIES';
export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIES_CUP_RESULT = 'MOVIES_CUP_RESULT';